name: Git Commit 
description: 'use this to clone add commit and push in repo'
inputs:
  repository:
    description: 'Repository Name Eg. shubham2698/pibm'
    required: true
  token:
    description: 'PAT'
    required: true
  file-pattern:
    description: 'file extension'
    required: true
  repository-name:
    description: 'repository name'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Git Config
      run: |
        git config --global user.name "Shubham Joshi"
        git config --global user.email "shubhamjoshi199826@gmail.com"
      shell: bash

    - name: Clone Repository
      run: | 
        git clone https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git
      shell: bash


    - name: Copy Files
      run: find . -type f -name "*${{ inputs.file-pattern }}" -exec cp {} ./${{ inputs.repository-name }} \;
      shell: bash

    - name: Add Commit push
      run: |
        cd ${{ inputs.repository-name }}
        git add .
        git commit -m "auto commit push"
        git push
      shell: bash
