name: Git Commit 
description: 'use this to clone add commit and push in repo'
inputs:
  repository:
    description: 'Repository Name Eg. shubham2698/pibm'
    required: true
  token:
    description: 'PAT'
    required: true
  file-name:
    description: 'file extension'
    required: true
  file-location:
    description: 'file location'
    required: true
  repository-name:
    description: 'repository name'
    required: true
  branch:
    description: 'branch'
    required: true
  destination-folder:
    description: 'destination folder'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Git Config
      run: |
        git config --global user.name "Shubham Joshi"
        git config --global user.email "shubhamjoshi199826@gmail.com"
      shell: bash

    - name: Clone Repository
      run: |
        if [ "${{ inputs.repository }}" != "." ]; then
          git clone https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git
          cd ${{ inputs.repository-name }}
          git checkout ${{ inputs.branch }}
          
        fi
      shell: bash


    - name: Copy Files
      run: |
        if [ "${{ inputs.repository }}" != "." ]; then
          src_path=${{ inputs.file-location }}
          result=""
          for file in ${{ inputs.file-name }}; do
            result+="$src_path$file "
          done
          cp $result ${{ inputs.repository-name }}/${{ inputs.destination-folder }}
          tree
        fi
      shell: bash

    - name: Add Commit push
      run: |
        if [ "${{ inputs.repository }}" != "." ]; then
          cd ${{ inputs.repository-name }}
          git checkout ${{ inputs.branch }}
          src_path=${{ inputs.destination-folder }}
          result=""
          for file in ${{ inputs.file-name }}; do
            result+="$src_path$file "
          done
          git add $result
          git commit -m "auto commit push"
          git push
        else
          git checkout ${{ inputs.branch }}
          src_path=${{ inputs.destination-folder }}
          result=""
          for file in ${{ inputs.file-name }}; do
            result+="$src_path$file "
          done
          git add $result
          git commit -m "auto commit push"
          git push
        fi
        
      shell: bash
