name: Git Commit 
description: 'use this to clone add commit and push in repo'
inputs:
  repository:
    description: 'Repository Name Eg. shubham2698/pibm'
    required: true
  token:
    description: 'PAT'
    required: true
  file-pattern:
    description: 'file extension'
    required: true
  repository-name:
    description: 'repository name'
    required: true
  branch:
    description: 'repository name'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Git Config
      run: |
        git config --global user.name "Shubham Joshi"
        git config --global user.email "shubhamjoshi199826@gmail.com"
      shell: bash

    - name: Clone Repository
      run: |
        if [ "${{ inputs.repository-name }}" != "." ]; then
          git clone https://${{ inputs.token }}@github.com/${{ inputs.repository }}.git
          
        fi
      shell: bash


    - name: Copy Files
      run: |
        if [ "${{ inputs.repository-name }}" != "." ]; then
          cp ${{ inputs.file-pattern }} ${{ inputs.repository-name }}
        fi
      shell: bash

    - name: Add Commit push
      run: |
        if [ "${{ inputs.repository-name }}" != "." ]; then
          cd ${{ inputs.repository-name }}
        fi
        git checkout ${{ inputs.branch }}
        git add ${{ inputs.file-pattern }}
        git commit -m "auto commit push"
        git push
      shell: bash
