name: Cargo Specific Version

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Add-Rust-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust 1.72
        run: | 
          curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup toolchain install nightly-2023-8-24
          rustup install default 1.72.0
          cargo --version
          rustc --version


    