name: Cargo Specific Version

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  Add-Rust-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Install Rust 1.72
      #   run: | 
      #     curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      #     rustup default nightly-2023-06-14
      #     cargo --version
      #     rustc --version
      
      - name: Install Rust
        id: install_rust
        run: |
          sudo apt-get update && sudo apt-get install -y clang
          sudo apt-get install pkg-config libssl-dev -y
          curl -y --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup default nightly-2023-06-09
          cargo --version
          rustc --version
          rustup show
          rustup component add rustfmt && cargo install cargo-audit && cargo install cargo2junit && cargo install cargo-llvm-cov
          cargo install markdown-test-report
          curl -LO https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-linux-amd64.tar.gz
          tar -xzvf pandoc-3.1.9-linux-amd64.tar.gz
          sudo mv pandoc-3.1.9/ /usr/local/bin/
          pandoc --version
          rm -r /home/runner/.cargo/registry   

      - name: Convert Json to HTML Pandoc
        run: |
          echo '{"name": "Shubham Joshi", "age": 35, "email": "imailshubhamjoshi@gmail.com"}' > sample.json
          markdown-test-report sample.json -o sample.md
          pandoc sample.md -o output.html
          cat output.html