name: Docker ENV

on:
  push:
    branches:
      - none
  workflow_dispatch:

jobs:
    Docker-Env:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Docker Build run
          run: |
            cd dockerfile
            docker build --build-arg VARIABLE=${{ secrets.DOCKERHUB_USERNAME }} -t test_env .
            docker run test_env