name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Files ( Main Repo Files )
          run: |
            touch git-commit-v1/auto_generated_4.txt
            touch git-commit-v1/auto_generated_4.sh

        - name: Git Commit
          uses: ./git-commit-v1
          with:
            repository: shubham2698/pibm_ra_13250
            repository-name: pibm_ra_13250
            branch: main
            token: ${{ secrets.PAT }}
            file-location: "./git-commit-v1/"
            file-name: "auto_generated_4.txt auto_generated_4.sh"
            destination-folder: "PDF"
            