name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Files ( Main Repo Files )
          run: touch auto_generated.txt

        - name: Git Commit
          uses: ./git-commit-v1
          with:
            repository: shubham2698/pibm_ra_13250
            repository-name: pibm_ra_13250
            token: ${{ secrets.PAT }}
            file-pattern: auto_generated.txt
            