name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Clone Repo and Add files
          run: |
            git clone https://github.com/shubham2698/iosapp
            touch random_3.txt

        - name: Commit changes and push
          id: commit_and_push
          uses: ./git-commit-v1
          with:
            branch: "main"
            file_pattern: './*.txt'
            commit_user_name: "shubham-vodafone"
            commit_user_email: "shubhamjoshi199826@gmail.com"
            commit_author: "Shubham Joshi"
            repository: "iosapp"