name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Files ( Main Repo Files )
          run: touch random_file.txt

        - name: Git Commit
          uses: ./git-commit-v1
          with:
            repository: .
            repository-name: .
            token: ${{ secrets.PAT }}
            file-pattern: random_file.txt
            