name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Files ( Main Repo Files )
          run: |
            touch auto_generated_3.txt
            touch auto_generated_3.sh

        - name: Git Commit
          uses: ./git-commit-v1
          with:
            repository: .
            repository-name: .
            branch: main
            token: ${{ secrets.PAT }}
            file-pattern: "auto_generated_3.txt"
            destination-folder: "git-commit-v1"
            