name: Git Commit Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    Git_Commit_Push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        # - name: Clone Repo , Add Files , Commit , Push
        #   run: |
        #     git config --global user.email "shubhamjoshi199826@gmail.com"
        #     git config --global user.name "Shubham Joshi"
        #     mkdir -p ~/.ssh/
        #     echo "${{ secrets.SSH_PRV }}" > ~/.ssh/id_ed25519
        #     chmod 600 ~/.ssh/id_ed25519
        #     ssh-keyscan github.com >> ~/.ssh/known_hosts
        #     git clone git@github.com:shubham2698/iosapp.git
        #     touch git-commit-v1/random_3.txt
        #     cp git-commit-v1/random_3.txt iosapp
        #     cd iosapp
        #     tree
        #     git add random_3.txt
        #     git commit -m "auto commit and push"
        #     git push

        - name: Git Commit
          uses: ./report-to-slack
          with:
            repository: shubham2698/pibm_ra_13250
            token: ${{ secrets.PAT }}