name: Go Lang Test Case HTML Report

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  GO_Lang_HTML_Report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Lang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report@latest

      
      - name: Execute Go Tests
        run: |
          cd go-tests
          go mod init github.com/shubham2698/go-lang-report-html
          go mod tidy
          go test -json > report.json
          # go-junit-report < report.json > report.html
          cat report.json
          tree

      # - name: Upload HTML report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-report
      #     path: go-tests/report.html