name: Go Lang Test Case HTML Report

on:
  push:
    branches:
      - none
  workflow_dispatch:


jobs:
  GO_Lang_HTML_Report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go Lang
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'
      
      - name: Execute Go Tests
        run: |
          cd go-tests
          go install github.com/vakenbolt/go-test-report@latest
          go mod init github.com/shubham2698/go-lang-report-html
          go mod tidy
          go test -json | go-test-report
          cat test_report.html
          tree

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: go-tests/test_report.html