name: MySQL Server Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    mysql_server:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_ROOT_HOST: '%'
          ports:
            - 33306:3306

      name: setup-mysql-server
      continue-on-error: true
      steps:

      - name: Update and install dependencies
        run: |
          sleep 10
          sudo service mysql start
          docker ps

      - name: Grant privileges
        run: |
            mysql -h 127.0.0.1 -P 3306 -uroot -p
            
          

      