name: Slack Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    mysql_server:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: test_db
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
          ports:
            - 33306:3306

      name: setup-mysql-server
      continue-on-error: true
      steps:

      - name: Update and install dependencies
        run: |
          sudo systemctl start mysql
          docker ps

      - name: Grant privileges
        run: |
            sudo mysql -h 127.0.0.1 -u root --port=3306 --password=password -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password'"
          

      