name: MySQL Server Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    mysql_server:
      runs-on: ubuntu-latest
      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: rootpassword
          ports:
            - 33306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      name: setup-mysql-server
      continue-on-error: true
      steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update and install dependencies
        run: |
          docker ps

      - name: Grant privileges
        run: mysql -h 127.0.0.1 --port 33306 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS test_db;'

          

      