name: Slack Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    mysql_server:
      runs-on: ubuntu-latest

      services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
          ports:
            - 33306:3306

      name: setup-mysql-server
      continue-on-error: true
      steps:

      # - name: change root password
      #   run: |
      #     sudo mysqld_safe --skip-grant-tables &
      #     mysql -u root mysql
      #     UPDATE user SET Password=PASSWORD('rootpassword') WHERE User='root';
      #     FLUSH PRIVILEGES;
      #     quit

      - name: Update and install dependencies
        run: |
          sudo systemctl start mysql
          sudo apt-get install default-mysql-client xxd -y

      - name: Grant privileges
        run: |
          mysql -u root -p'rootpassword'
          

      