name: Git Commit Push

on:
  workflow_dispatch:

jobs:
    Send-slack-notification:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4 

        - name: Commit changes and push
          id: commit_and_push
          uses: ./git-commit-v1
          with:
            working_directory: ${{ github.action_path }}
            add:
              file1.txt
              file2.txt